apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trino
  namespace: trino-system
spec:
  gateways:
  - ingress-general-system/general-istio-ingress-gateway-https
  hosts:
  - trino.aaw-dev.cloud.statcan.ca
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trino.trino-system.svc.cluster.local
        port:
          number: 8080
      headers:
        request:
          add:
            x-forwarded-proto: "https"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: trino-server
  namespace: trino-system
spec:
  host: trino.trino-system.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: DISABLE
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trino
    heritage: Helm
    release: trino
  name: trino-headless
  namespace: trino-system
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: trino
    release: trino
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
