apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trino
  namespace: daaas-system
spec:
  gateways:
  - ingress-general-system/general-istio-ingress-gateway-https
  hosts:
  - trino.aaw-dev.cloud.statcan.ca
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trino.trino-system.svc.cluster.local
        port:
          number: 8080
      headers:
        request:
          add:
            x-forwarded-proto: "https"
