apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: daaas-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  destination:
    namespace: daaas-system
    name: in-cluster
  source:
    repoURL: 'https://github.com/StatCan/aaw-network-policies.git'
    path: .
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
