apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: The namespace != the system name
# This is a terminology difference between AAW and FDI
namespace: fdi-gateway-external-system

commonLabels:
  node.statcan.gc.ca/purpose: system
  system: fdi-gateway-unclassified-system

resources:
  - ../kustomize-gateway/overlays/gateway-bundle/

components:
  - ../kustomize-gateway/components/unclassified/
