apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-gateway-standard-system

commonLabels:
  node.statcan.gc.ca/purpose: system
  system: minio-gateway-standard-system

resources:
  - ../kustomize-gateway/overlays/gateway-rw/

components:
  - ../kustomize-gateway/components/unclassified/

# s~\.minio\.~.${namespace}.~g
patchesStrategicMerge:
- |-
   apiVersion: apps/v1
   kind: StatefulSet
   metadata:
     name: minio-gateway-etcd
   spec:
     template:
       spec:
         affinity:
           podAntiAffinity: {}
         containers:
           - name: etcd
             env:
               - name: MY_POD_NAME
                 valueFrom:
                   fieldRef:
                     fieldPath: metadata.name
               - name: ETCD_ADVERTISE_CLIENT_URLS
                 value: http://$(MY_POD_NAME).minio-gateway-etcd-headless.minio-gateway-standard-system.svc.cluster.local:2379,http://minio-gateway-etcd.minio-gateway-standard-system.svc.cluster.local:2379

               - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
                 value: "http://$(MY_POD_NAME).minio-gateway-etcd-headless.minio-gateway-standard-system.svc.cluster.local:2380"

               - name: ETCD_INITIAL_CLUSTER
                 value: "minio-gateway-etcd-0=http://minio-gateway-etcd-0.minio-gateway-etcd-headless.minio-gateway-standard-system.svc.cluster.local:2380"

- |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: minio-gateway
   spec:
     template:
       spec:
         containers:
         - name: minio
           env:
           - name: MINIO_SERVER_URL
             value: http://minio-gateway-api.minio-gateway-standard-system
           - name: MINIO_BROWSER_REDIRECT_URL
             value: http://minio-gateway-console.minio-gateway-standard-system
