apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: portal
  namespace: org-fdi-system
spec:
  version: 7.13.2
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: nodes
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300" 
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      spec:
        automountServiceAccountToken: true 
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          storageClassName: default
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 256Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: portal
  namespace: org-fdi-system
spec:
  version: 7.13.2
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: portal
  podTemplate:
    spec:
      automountServiceAccountToken: true
