# Source: profiles-controller/templates/deployment-buckets.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-controller-buckets
  labels:
    helm.sh/chart: profiles-controller-0.1.8
    app.kubernetes.io/name: profiles-controller
    app.kubernetes.io/instance: profiles-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: profiles-controller
      app.kubernetes.io/instance: profiles-controller
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-configmap: profiles-controller-vault-agent-config
        vault.hashicorp.com/agent-pre-populate: 'false'
      labels:
        app.kubernetes.io/name: profiles-controller
        app.kubernetes.io/instance: profiles-controller
    spec:
      serviceAccountName: profile-configurator
      securityContext: {}
      containers:
        - name: profiles-controller
          securityContext: {}
          image: k8scc01covidacr.azurecr.io/profiles-controller:3989df47071aa03c695de1acfa0cfcdb8b063d05
          imagePullPolicy: IfNotPresent
          args:
            - buckets
          env:
            - name: MINIO_INSTANCES
              value: minio_standard,minio_protected_b,minio_gateway_standard,minio_gateway_premium
            - name: VAULT_AGENT_ADDR
              value: http://127.0.0.1:8100
          resources: {}
