apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifest.yaml

patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: gitea-unclassified-init
  patch: |-
    - op: replace
      path: /stringData/init_directory_structure.sh
      value: |
        #!/usr/bin/env bash
        set -euo pipefail
        # BEGIN: initPreScript
        # END: initPreScript

        set -x
        mkdir -p /data/git/.ssh
        chmod -R 700 /data/git/.ssh
        [ ! -d /data/gitea/conf ] && mkdir -p /data/gitea/conf
        mkdir -p /data/gitea/templates
        [ -s /data/gitea/templates/custom ] || ln -s /custom /data/gitea/templates/custom
        # prepare temp directory structure
        mkdir -p "${GITEA_TEMP}"
        chmod ug+rwx "${GITEA_TEMP}"
- target:
    version: v1
    kind: StatefulSet
    name: gitea-unclassified
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
    - op: add
      path: /spec/template/spec/initContainers/2/securityContext
      value:
        runAsUser: 1337
