apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifest.yaml

patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: gitea-unclassified-init
  patch: |-
    - op: replace
      path: /stringData/init_directory_structure.sh
      value: |
        #!/usr/bin/env bash
        set -euo pipefail
        # BEGIN: initPreScript
        # END: initPreScript

        set -x
        mkdir -p /data/git/.ssh
        chmod -R 700 /data/git/.ssh
        [ ! -d /data/gitea/conf ] && mkdir -p /data/gitea/conf
        mkdir -p /data/gitea/templates
        [ -s /data/gitea/templates/custom ] || ln -s /custom /data/gitea/templates/custom
        # prepare temp directory structure
        mkdir -p "${GITEA_TEMP}"
        chmod ug+rwx "${GITEA_TEMP}"
- target:
    version: v1
    kind: StatefulSet
    name: gitea-unclassified
  patch: |-
    - op: remove
      path: /spec/template/spec/initContainers/2
    - op: add
      path: /spec/template/spec/containers/0/command
      value:
        - /bin/bash
    - op: add
      path: /spec/template/spec/containers/0/args
      value:
        - -c
        - |
          sleep 1
          set -euo pipefail

          echo '==== BEGIN GITEA CONFIGURATION ===='

          { # try
            gitea migrate
          } || { # catch
            echo "Gitea migrate might fail due to database connection...This init-container will try again in a few seconds"
            exit 1
          }


          function configure_admin_user() {
            local ACCOUNT_ID=$(gitea admin user list --admin | grep -e "\s\+${GITEA_ADMIN_USERNAME}\s\+" | awk -F " " "{printf \$1}")
            if [[ -z "${ACCOUNT_ID}" ]]; then
              echo "No admin user '${GITEA_ADMIN_USERNAME}' found. Creating now..."
              gitea admin user create --admin --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}" --email "gitea@local.domain" --must-change-password=false
              echo '...created.'
            else
              echo "Admin account '${GITEA_ADMIN_USERNAME}' already exist. Running update to sync password..."
              gitea admin user change-password --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}"
              echo '...password sync done.'
            fi
          }
          configure_admin_user
          echo '==== END GITEA CONFIGURATION ===='
          exec /usr/local/bin/docker-entrypoint.sh
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: SSH_LISTEN_PORT
          value: "2222"
        - name: SSH_PORT
          value: "22"
        - name: GITEA_APP_INI
          value: /data/gitea/conf/app.ini
        - name: GITEA_CUSTOM
          value: /data/gitea
        - name: GITEA_WORK_DIR
          value: /data
        - name: GITEA_TEMP
          value: /tmp/gitea
        - name: TMPDIR
          value: /tmp/gitea
        - name: GITEA_ADMIN_USERNAME
          value: "superuser"
        - name: GITEA_ADMIN_PASSWORD
          value: "password"
