apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: daaas
  namespace: shared-daaas-system
spec:
  version: 7.16.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: nodes
    count: 2
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      spec:
        nodeSelector:
          agentpool: generaltemp
        automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 4
            requests:
              cpu: "4"
              memory: 8Gi
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          storageClassName: default
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 512Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: daaas
  namespace: shared-daaas-system
spec:
  version: 7.16.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: daaas
  secureSettings:
  - secretName: daaas-kibana-secrets
  podTemplate:
    spec:
      automountServiceAccountToken: true
