apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: es
  namespace: daaas-system
spec:
  gateways:
    - ingress-general-system/general-istio-ingress-gateway-https
  hosts:
    - daaas-system-daaas-es.aaw-dev.cloud.statcan.ca
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: daaas-es-http.daaas-system.svc.cluster.local
            port:
              number: 9200
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: es
  namespace: daaas-system
spec:
  host: daaas-es-http.daaas-system.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kb
  namespace: daaas-system
spec:
  gateways:
    - ingress-general-system/general-istio-ingress-gateway-https
  hosts:
    - daaas-system-daaas-kb.aaw-dev.cloud.statcan.ca
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: daaas-kb-http.daaas-system.svc.cluster.local
            port:
              number: 5601
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kb
  namespace: daaas-system
spec:
  host: daaas-kb-http.daaas-system.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
