apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: etcd
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 6.2.9
  releaseName: minio-gateway-etcd
  values: values.yaml
