---
# Source: minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-gateway
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: minio-gateway
    helm.sh/chart: minio-8.0.1
    app.kubernetes.io/instance: minio-gateway
secrets:
  - name: minio-gateway
---
# Source: minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-gateway
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: minio-gateway
    helm.sh/chart: minio-8.0.1
    app.kubernetes.io/instance: minio-gateway
spec:
  type: ClusterIP
  
  ports:
    - name: minio-api
      port: 9000
      targetPort: minio-api
      nodePort: null
    - name: minio-console
      port: 9001
      targetPort: minio-console
      nodePort: null
  selector:
    app.kubernetes.io/name: minio-gateway
    app.kubernetes.io/instance: minio-gateway
---
# Source: minio/templates/gateway/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-gateway
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: minio-gateway
    helm.sh/chart: minio-8.0.1
    app.kubernetes.io/instance: minio-gateway
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-gateway
      app.kubernetes.io/instance: minio-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-gateway
        helm.sh/chart: minio-8.0.1
        app.kubernetes.io/instance: minio-gateway
    spec:
      
      serviceAccountName: minio-gateway
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: minio-gateway
                    app.kubernetes.io/instance: minio-gateway
                namespaces:
                  - "kubeflow"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: minio
          image: k8scc01covidacr.azurecr.io/minio:2021.5.27-debian-10-r8
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          command:
            - minio
          args:
            - --certs-dir
            - /opt/bitnami/minio/certs
            - gateway
            - azure
          env:
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: azure-blob-storage
                  key: storageAccountName
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-blob-storage
                  key: storageAccountKey
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-gateway-secret
                  key: access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-gateway-secret
                  key: secret-key
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
            - name: MINIO_ETCD_ENDPOINTS
              value: http://etcd-minio-gateway-headless:2379/
            - name: MINIO_IAM_OPA_URL
              value: http://minio-opa:8181/v1/data/httpapi/authz
          envFrom:
          ports:
            - name: minio-api
              containerPort: 9000
              protocol: TCP
            - name: minio-console
              containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
      volumes:
