apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fdi-gateway-protected-b-system

commonLabels:
  node.statcan.gc.ca/purpose: system
  system: fdi-gateway-protected-b-system

resources:
  - ../kustomize-gateway/overlays/gateway-bundle/

components:
  - ../kustomize-gateway/components/protected-b/
  # - ../kustomize-gateway/components/general-pool/

replicas:
- name: minio-gateway
  count: 0
- name: minio-gateway-etcd
  count: 0
- name: minio-gateway-opa
  count: 0
