apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: daaas-system
  namespace: daaas-system
spec:
  gateways:
    - ingress-general-system/general-istio-ingress-gateway-https
  hosts:
    - daaas-system-argocd.aaw-dev.cloud.statcan.ca
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: daaas-system-server.daaas-system.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: daaas-system-server
  namespace: daaas-system
spec:
  host: daaas-system-server.daaas-system.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
