apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-state-controller
  namespace: daaas-system
spec:
  selector:
    matchLabels:
      app: profile-state-controller
  template:
    metadata:
      labels:
        app: profile-state-controller
    spec:
      serviceAccountName: profile-state-controller
      containers:
        - name: profile-state-controller
          image: k8scc01covidacr.azurecr.io/profile-state-controller:9ab98683f3381decb77cde2116617082bada7121
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
