apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-state-controller
  namespace: daaas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-state-controller
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "rolebindings"
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - "kubeflow.org"
    resources:
      - "profiles"
    verbs:
      - update
      - watch
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: profile-state-controller
subjects:
  - kind: ServiceAccount
    name: profile-state-controller
    namespace: daaas-system
roleRef:
  kind: ClusterRole
  name: profile-state-controller
  apiGroup: rbac.authorization.k8s.io
