apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-gateway-premium-system

commonLabels:
  node.statcan.gc.ca/purpose: system
  system: minio-gateway-premium-system

resources:
  - ../kustomize-gateway/overlays/gateway-rw/

components:
  - ../kustomize-gateway/components/unclassified/

