apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-templates
  namespace: statcan-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  destination:
    namespace: statcan-system
    name: in-cluster
  source:
    repoURL: 'https://github.com/StatCan/gatekeeper-policies.git'
    path: .
    targetRevision: feat-aaw-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
