apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-config
  namespace: monitoring-system
type: Opaque
stringData:
  beat.yml: |
    heartbeat.monitors:
      - name: elasticsearch
        tags: ["internal", "${NS_NAME}"]
        type: tcp
        schedule: "@every 5s"
        hosts: ["elastic-monitoring-es-http.monitoring-system.svc:9200"]
      - name: kibana
        tags: ["internal", "${NS_NAME}"]
        type: tcp
        schedule: "@every 5s"
        hosts: ["kibana-monitoring-kb-http.monitoring-system.svc:5601"]
    processors:
      - add_observer_metadata:
          cache.ttl: 5m
          geo:
            name: ${NODE_NAME}
