apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: minio-gateway
    patch: |-
      - op: add
        path: "/spec/template/metadata/labels/aadpodidbinding"
        value: fdi-sa-identity
