apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - role.yaml
  - serviceaccount.yaml
  - rolebinding.yaml
  - aad-refresher.yaml

configMapGenerator:
  - name: aad-refresher-script
    files:
      - script.sh

generatorOptions:
  disableNameSuffixHash: true
