apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-configurator
  namespace: daaas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-configurator
rules:
- apiGroups:
    - ''
  resources:
    - 'secrets'
    - 'serviceaccounts'
  verbs:
    - watch
    - list
- apiGroups:
    - ''
  resources:
    - 'secrets'
  verbs:
    - create
- apiGroups:
    - ''
  resources:
    - 'secrets'
  verbs:
    - get
    - create
    - update
    - delete
  resourceNames:
    - image-pull-secret
- apiGroups:
    - ''
  resources:
    - 'serviceaccounts'
  verbs:
    - get
    - update
  resourceNames:
    - default-editor
- apiGroups:
    - 'kubeflow.org'
  resources:
    - 'profiles'
    - 'poddefaults'
  verbs:
    - get
    - list
    - watch
    - create
    - update
- apiGroups:
    - ''
  resources:
    - 'events'
  verbs:
    - create
    - patch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - 'rolebindings'
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiGroups:
    - networking.istio.io
  resources:
    - 'envoyfilters'
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: profile-configurator
subjects:
- kind: ServiceAccount
  name: profile-configurator
  namespace: daaas-system
roleRef:
  kind: ClusterRole
  name: profile-configurator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seldon-user
rules:
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - seldondeployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seldon-profile-configurator
subjects:
- kind: ServiceAccount
  name: profile-configurator
  namespace: daaas-system
roleRef:
  kind: ClusterRole
  name: seldon-user
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-profile-configurator
subjects:
- kind: ServiceAccount
  name: profile-configurator
  namespace: daaas-system
roleRef:
  kind: ClusterRole
  name: argo
  apiGroup: rbac.authorization.k8s.io
