apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-test
  namespace: daaas-system
spec:
  project: default
  destination:
    namespace: daaas-system
    name: in-cluster
  source:
    repoURL: 'https://github.com/statcan/aaw-argocd-manifests.git'
    path: kustomize-test/kustomize
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
