# Namespace and secrets done from terraform
---
# Access notebooks across the cluster, and get read on the ConfigMap for an image to update to.
# Removed update from notebooks since w/ imago just restart pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notebook-img-cleanup-cluster-role
rules:
  - apiGroups: ["kubeflow.org"]
    resources: ["notebooks"] 
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmap"]
    verbs: ["get"]
---
#Service Account
kind: ServiceAccount
apiVersion: v1
metadata:
  name: notebook-img-cleanup-sa
  namespace: notebook-cleanup-system
---
# RoleBinding, specifically for Clusterroles
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notebook-img-cleanup-crb
subjects:
- kind: ServiceAccount
  name: notebook-img-cleanup-sa
  namespace: notebook-cleanup-system
roleRef:
  kind: ClusterRole
  name: notebook-img-cleanup-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-cleanup
  namespace: notebook-cleanup-system
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: notebook-img-cleanup-sa
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          containers:
          - name: image-cleanup-job
            image: k8scc01covidacr.azurecr.io/notebook-cleanup:ca2a0c7679e61a83f847a99bae53913ecd7ef3d1
            imagePullPolicy: IfNotPresent
            env:
              - name: JFROG_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: jfrog-aaw-notebook-scanning-secret
                    key: jfrog_aaw_username
              - name: JFROG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jfrog-aaw-notebook-scanning-secret
                    key: jfrog_aaw_encrypted_password
