apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-cr-workflow
subjects:
- kind: ServiceAccount
  name: deleting-workflow
  namespace: daaas-system
roleRef:
  kind: ClusterRole
  name: delete-workflow
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-workflow
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "watch", "list", "delete"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deleting-workflow
  namespace: daaas-system
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argo-workflow
  namespace: daaas-system
spec:
  concurrencyPolicy: Forbid
  schedule: "0 22 * * 1-5"
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: deleting-workflow
          restartPolicy: Never
          containers:
          - name: argocli
            image: argoproj/argocli:latest
            args: ["delete", "--all-namespaces" , "-l" , "scheduledworkflows.kubeflow.org/isOwnedByScheduledWorkflow=true", "--older" ,"5d"]
