apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inferenceservices-controller
  namespace: daaas-system
spec:
  project: platform
  destination:
    namespace: daaas-system
    name: in-cluster
  source:
    repoURL: 'https://statcan.github.io/charts'
    chart: inferenceservices-controller
    targetRevision: 0.0.1
    helm:
      releaseName: inferenceservices-controller
      values: |
        image:
          repository: k8scc01covidacr.azurecr.io/inferenceservices-controller
          tag: fc6148fa4c1b5c3d2cae7d250ab3dc8fb0c99083
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
