apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daaas-system
spec:
  generators:
  - git:
      repoURL: https://github.com/statcan/aaw-argocd-manifests.git
      revision: HEAD
      directories:
      - path: daaas-system/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/statcan/aaw-argocd-manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
