apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-gateway-standard-ro-system

commonLabels:
  node.statcan.gc.ca/purpose: system
  system: minio-gateway-standard-system

resources:
  - ../kustomize-gateway/overlays/gateway-ro/

components:
  - ../kustomize-gateway/components/protected-b/
