apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: protected-b
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-protected-b
  servers:
  - hosts:
    - '*'
    port:
      name: http-protected-b
      number: 80
      protocol: HTTP2
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https-protected-b
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES128-GCM-SHA256
      credentialName: wildcard-tls
      maxProtocolVersion: TLSV1_2
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
