apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kubeflow
data:
  fluent.conf: |
    <filter **>
      @type grep
      <exclude>
        key log
        pattern ^.* (obs|exp|nochange): .*$
      </exclude>
    </filter>

    <match **>
      @type default
    </match>
