apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubeflow
  namespace: daaas-system
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
