apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: etcd-minio-gateway
spec:
  host: etcd-minio-gateway-headless.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
