apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-user-profiles
  namespace: daaas-system
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: default
  source: 
    repoURL: https://github.com/blairdrummond/fake-kubeflow-profiles.git
    targetRevision: master
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
