apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-profiles
  namespace: daaas-system
spec:
  project: default
  destination:
    namespace: daaas-system
    name: in-cluster
  source:
    repoURL: 'https://github.com/StatCan/aaw-kubeflow-profiles.git'
    path: .
    targetRevision: main
  ignoreDifferences:
  - group: ""
    kind: Namespace
    jsonPointers:
    - /metadata/resourceVersion
    - /metadata/ownerReferences
    - /metadata/uid
    - /metadata/selfLink
    - /metadata/labels
    - /spec
  - group: kubeflow.org
    kind: Profile
    jsonPointers:
    - /metadata/resourceVersion
    - /metadata/uid
    - /metadata/selfLink
    - /metadata/finalizers
    - /metadata/generation
    - /metadata/labels
    - /spec/resourceQuotaSpec
  syncPolicy: {}
  #  automated:
  #    prune: true
  #    selfHeal: true
